version: '3'

services:
  web-app:
    build:
      context: .
    container_name: books_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    command: bash entrypoint.sh
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: books_db
    env_file:
      - ./.env
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    restart: unless-stopped

volumes:
  pgdbdata: