version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: books_user
      POSTGRES_PASSWORD: 123
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped