# Generated by Django 4.2.2 on 2023-06-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='middle_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.ManyToManyField(to='books.publisher'),
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(to='books.author'),
        ),
    ]
