# Generated by Django 4.2.2 on 2023-07-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Cus', 'Customer'), ('Ven', 'Vendor'), ('Adm', 'Admin (superuser)')], default='Cus'),
        ),
    ]
